spring.cloud.config.server.git.uri: https://git.oschina.net/ey/spring-cloud-config.git

server.port: 8888

# Spring properties
spring:
  application:
     name: configserver

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/